return {}
-- return {
--   {
--     "haya14busa/vim-asterisk",
--     keys = {
--       { "n",  mode = "n" },
--       { "*",  mode = "n" },
--       { "#",  mode = "n" },
--       { "g#", mode = "n" },
--     },
--     config = function()
--       vim.api.nvim_set_keymap("n", "*", [[<Plug>(asterisk-z*)<Cmd>lua require('hlslens').start()<CR>]], {})
--       vim.api.nvim_set_keymap("n", "#", [[<Plug>(asterisk-z#)<Cmd>lua require('hlslens').start()<CR>]], {})
--       vim.api.nvim_set_keymap("n", "g*", [[<Plug>(asterisk-gz*)<Cmd>lua require('hlslens').start()<CR>]], {})
--       vim.api.nvim_set_keymap("n", "g#", [[<Plug>(asterisk-gz#)<Cmd>lua require('hlslens').start()<CR>]], {})

--       vim.api.nvim_set_keymap("x", "*", [[<Plug>(asterisk-z*)<Cmd>lua require('hlslens').start()<CR>]], {})
--       vim.api.nvim_set_keymap("x", "#", [[<Plug>(asterisk-z#)<Cmd>lua require('hlslens').start()<CR>]], {})
--       vim.api.nvim_set_keymap("x", "g*", [[<Plug>(asterisk-gz*)<Cmd>lua require('hlslens').start()<CR>]], {})
--       vim.api.nvim_set_keymap("x", "g#", [[<Plug>(asterisk-gz#)<Cmd>lua require('hlslens').start()<CR>]], {})
--     end,
--   },
--   {
--     "kevinhwang91/nvim-hlslens",
--     keys = {
--       { "n",  mode = "n" },
--       { "*",  mode = "n" },
--       { "#",  mode = "n" },
--       { "g#", mode = "n" },
--     },
--     config = function()
--       require("hlslens").setup({
--         auto_enable = true,
--         nearest_only = true,
--         nearest_float_when = "never",
--         calm_down = true,
--       })

--       -- local opts = { noremap = true, silent = true }
--       -- Hlslens
--       -- vim.api.nvim_set_keymap(
--       --   "n",
--       --   "n",
--       --   [[<Cmd>execute('normal! ' . v:count1 . 'n')<CR><Cmd>lua require('hlslens').start()<CR>]],
--       --   opts
--       -- )
--       -- vim.api.nvim_set_keymap(
--       --   "n",
--       --   "N",
--       --   [[<Cmd>execute('normal! ' . v:count1 . 'N')<CR><Cmd>lua require('hlslens').start()<CR>]],
--       --   opts
--       -- )
--       -- vim.api.nvim_set_keymap("n", "*", [[*<Cmd>lua require('hlslens').start()<CR>]], opts)
--       -- vim.api.nvim_set_keymap("n", "#", [[#<Cmd>lua require('hlslens').start()<CR>]], opts)
--       -- vim.api.nvim_set_keymap("n", "g*", [[g*<Cmd>lua require('hlslens').start()<CR>]], opts)
--       -- vim.api.nvim_set_keymap("n", "g#", [[g#<Cmd>lua require('hlslens').start()<CR>]], opts)
--     end,
--   },
-- }
