return {}
-- return {
--   'gabrielpoca/replacer.nvim',
--   opts = { rename_files = true },
--   keys = {
--     {
--       '<leader>hH',
--       function() require('replacer').run() end,
--       desc = "run replacer.nvim"
--     }
--   }
-- }
